// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gufoqfaahxcffffrjiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1Zm9xZmFhaHhjZmZmZnJqaWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjk3MjcsImV4cCI6MjA2NDYwNTcyN30.jd9ntSgXk1_IzWKlDixtnQswAoI7S8SxdF3_fqKhaY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);